# Generated by Django 5.2.5 on 2025-08-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100, verbose_name="品牌")),
                ("code", models.CharField(max_length=20, verbose_name="股票代码")),
                ("name", models.CharField(max_length=100, verbose_name="股票名称")),
                ("date", models.DateField(verbose_name="日期")),
                (
                    "open",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="开盘价"
                    ),
                ),
                (
                    "close",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="收盘价"
                    ),
                ),
                (
                    "high",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="最高价"
                    ),
                ),
                (
                    "low",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="最低价"
                    ),
                ),
                ("volume", models.BigIntegerField(verbose_name="成交量")),
                (
                    "turnover",
                    models.DecimalField(
                        decimal_places=2, max_digits=16, verbose_name="成交额"
                    ),
                ),
                (
                    "amplitude",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="振幅(%)"
                    ),
                ),
                (
                    "change_pct",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="涨跌幅(%)"
                    ),
                ),
                (
                    "change_amt",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="涨跌额"
                    ),
                ),
                (
                    "turnover_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="换手率(%)"
                    ),
                ),
            ],
            options={
                "verbose_name": "股票数据",
                "verbose_name_plural": "股票数据",
                "indexes": [
                    models.Index(
                        fields=["brand", "date"], name="stock_stock_brand_b14ad3_idx"
                    ),
                    models.Index(
                        fields=["code", "date"], name="stock_stock_code_954b59_idx"
                    ),
                ],
                "unique_together": {("brand", "date")},
            },
        ),
    ]
